name: Season9
version: '1.0'
main: com.bernardo.season9
api-version: '1.20'
commands:
  regras:
    description: Mostra as regras do servidor
    usage: /regras
  loja:
    description: Mostra como fazer loja no servidor
    usage: /loja
  voice:
    description: Voice
    usage: /voice
  terreno:
    description: Terreno
    usage: /terreno
  tabela:
    description: Tabela
    usage: /tabela
  sub:
    description: Sub
    usage: /sub
  vip:
    description: Vip
    usage: /vip
  item1:
    description: Recebe o item colecion치vel da abertura do servidor
    usage: /item1
  item2:
    description: Recebe o item colecion치vel do r/Place 2023
    usage: /item2
  item3:
    description: Recebe o item colecion치vel da Abertura do Nether
    usage: /item3
  item4:
    description: Recebe o item colecion치vel do Prefeito do servidor
    usage: /item4