name: Season9
version: '${project.version}'
main: com.bernardo.season9
api-version: '1.20'
commands:
  regras:
    description: Mostra as regras do servidor
    usage: /regras
  item1:
    description: Recebe um tronco de árvore cherry customizado
    usage: /item1
