name: Season9
version: '${project.version}'
main: com.bernardo.season9
api-version: '1.20'
commands:
  regras:
    description: Mostra as regras do servidor
    usage: /regras
  loja:
    description: Mostra como fazer loja no servidor
    usage: /loja
  voice:
    description: Voice
    usage: /voice
  terreno:
    description: Terreno
    usage: /terreno

  item1:
    description: Recebe o item colecionável da abertura do servidor
    usage: /item1
  item2:
    description: Recebe o item colecionável do r/Place 2023
    usage: /item2
  item3:
    description: Recebe o item colecionável da Abertura do Nether
    usage: /item3
